name: merge
run-name: ${{ github.actor }} is merging ${{github.head_ref}} to ${{github.base_ref}}
on:
  pull_request_target:
    types:
      - closed

jobs:
  pull_request_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://styled-todo-server.vercel.app/github/mergePR'
          method: 'POST'
          data: '{"author": "${{github.actor}}", "request_id": "${{github.event.pull_request.number}}", "from_branch": "${{github.head_ref}}", "to_branch": "${{github.base_ref}}", "createdAt": "${{github.event.repository.updated_at}}"}'
Footer
